version: "3"

services:
  shiny:
    image: registry.triply.cc/coda/rshiny-app:${TAG}
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "3838:3838"
    volumes:
      - coda-data:/srv/shiny-server/data/

volumes:
  coda-data:
